### ISSUE TITLE
Problem with address color and space in urlbar with PM 28

### ISSUE THREAD

**Issue by andreat** [Lootyhoof/moonola#1]
After the upgrade to Pale Moon 28, the urlbar does not show anymore secure addresses in green; moreover all addresses have no left padding, so they are glued with the address status box.
The attached pictures show the difference between Pale Moon 27 and Pale Moon 28.

It seems like something has changed in the identifiers of the urlbar so the corresponding CSS entries are no more applied.

![pm27](https://user-images.githubusercontent.com/469213/44318817-e22bc800-a427-11e8-8288-6ec5db5f92e9.png)
![pm28](https://user-images.githubusercontent.com/469213/44318818-e22bc800-a427-11e8-89d9-1ac1f1092648.png)

**Comment by Lootyhoof** [comment]
Sorry for the delay. I'm still tracking down what's causing this, hence this issue is still present in v1.9.0.

I'll try to get this sorted soon.

**Comment by Lootyhoof** [comment]
Spotted it. This is now in v1.9.1.

Sorry about the confusion!
